name: Personal Terminal
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Start tmate Session
        uses: mxschmitt/action-tmate@v3

